# Generated by Django 5.1.1 on 2024-09-08 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='minutes',
            field=models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='timer',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='timer',
            name='seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)]),
        ),
    ]
